# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: NPM Install
        run: npm install
      # - name: NPM Test
      #   run: npm test
      - name: Build
        run: npm run build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy GitHub Pages
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        npm install
    - name: Config Git
      run: |
        git config --global user.name 'Huan @ GitHub Action'
        git config --global user.email 'zixia@zixia.net'
    - name: Create orphan branch for gh-pages
      run: |
        git checkout --orphan gh-pages
        git reset --hard
        git commit --allow-empty -m "Orphan init"
        git checkout main
    - name: Bind git worktree with dist/spacle-ng folder and gh-pages branch
      run: |
        rm -fr gh-pages
        git worktree add gh-pages gh-pages
    - name: Build
      run: |
        npm run build
        mv dist/spacle-ng/* gh-pages
        echo www.chatie.io > gh-pages/CNAME
    - name: Deploy
      run: |
        pushd gh-pages
        git add --all
        git commit -m "$(jq -r .version ../package.json)"
        git push -f origin gh-pages
        popd
    - name: Unbind gh-pages folder from gh-pages branch
      run: |
        git worktree remove gh-pages
        git branch -D gh-pages
        rm -fr gh-pages

